# Generated by Django 3.0.5 on 2020-08-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_active', models.PositiveSmallIntegerField(choices=[(5, '아주 많음'), (4, '많음'), (3, '보통'), (2, '적음'), (1, '아주 적음')], verbose_name='활발함')),
                ('char_hair', models.PositiveSmallIntegerField(choices=[(5, '아주 많음'), (4, '많음'), (3, '보통'), (2, '적음'), (1, '아주 적음')], verbose_name='털날림')),
                ('char_barking', models.PositiveSmallIntegerField(choices=[(5, '아주 많음'), (4, '많음'), (3, '보통'), (2, '적음'), (1, '아주 적음')], verbose_name='짖음')),
                ('char_social', models.PositiveSmallIntegerField(choices=[(5, '아주 많음'), (4, '많음'), (3, '보통'), (2, '적음'), (1, '아주 적음')], verbose_name='사교성')),
                ('char_indep', models.PositiveSmallIntegerField(choices=[(5, '아주 많음'), (4, '많음'), (3, '보통'), (2, '적음'), (1, '아주 적음')], verbose_name='독립성')),
                ('char_lovely', models.PositiveSmallIntegerField(choices=[(5, '아주 많음'), (4, '많음'), (3, '보통'), (2, '적음'), (1, '아주 적음')], verbose_name='애교')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='이름')),
                ('gender', models.CharField(choices=[('F', '여자'), ('M', '남자')], max_length=20, verbose_name='성별')),
                ('age', models.PositiveSmallIntegerField(null=True, verbose_name='나이')),
                ('neutered', models.CharField(choices=[('O', 'O'), ('X', 'X')], max_length=20, verbose_name='중성화여부')),
                ('a_number', models.CharField(max_length=20, verbose_name='공고번호')),
                ('shelter', models.CharField(max_length=200, verbose_name='유기견 보호소')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('images', models.ImageField(blank=True, upload_to='profiles/%Y/%m/%d')),
                ('available_adopt', models.BooleanField(default=True, verbose_name='입양 가능 여부')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Character')),
            ],
            options={
                'ordering': ['-created'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
